### ISSUE TITLE
libritts missing `Gender.txt`

### ISSUE THREAD

**Issue by eschmidbauer** [CODEJIN/NaturalSpeech2#2]
Hi-thanks for sharing this work!
 I'm trying to train based on libritts but it appears the `Pattern_Generator.py` is looking for a file that does not exist, named `Gender.txt`
I was able to find speaker info file for libritts which contains the gender but it doesn't match the expected format of `Gender.txt`
See attached speaker_info.txt
[speaker_info.txt](https://github.com/CODEJIN/NaturalSpeech2/files/11508044/speaker_info.txt)

**Comment by eschmidbauer** [comment]
I was able to use the speaker info file if i made this change. but im curious if this is the right file since the code references a `Gender.txt`
```
--- a/Pattern_Generator.py
+++ b/Pattern_Generator.py
@@ -685,7 +685,8 @@ def Libri_Info_Load(path: str):
     emotion_dict = {path: 'Neutral' for path in paths}
     language_dict = {path: 'English' for path in paths}
     gender_dict = {
-        'Libri.{:04d}'.format(int(line.strip().split('\t')[0])): line.strip().split('\t')[1]
+        'Libri.{:04d}'.format(int(line.strip().split('|')[0])): line.strip().split('|')[1]
```

**Comment by CODEJIN** [comment]
Dear ecshmidbauer,

Hello, thank you for your interest in the repository. The file you mentioned 'Gender.txt' was a file I created for my convenience. Instead of sharing that file, I decided it would be better to modify `Pattern_Generator.py`, so that it can extract gender information from the default dataset. I have pushed the updated version of `Pattern_Generator.py` without that file. Please check this [commit](https://github.com/CODEJIN/NaturalSpeech2/commit/7f910a625fefbe4e22c5703444203f990724f5a9).

Best regards,

Heejo

**Comment by eschmidbauer** [comment]
thanks - would you be able to share `SPEAKERS.txt` ? I cannot find it in the default libritts dataset [here](https://www.openslr.org/60/) or [here](https://arxiv.org/abs/1904.02882)

**Comment by CODEJIN** [comment]
Here is the file: [SPEAKERS.txt](https://github.com/CODEJIN/NaturalSpeech2/files/11508321/SPEAKERS.txt)

However, that's strange. When I obtained the dataset, this file 'SPEAKERS.TXT' was included in the LibriTTS compressed file. I'm not sure if the dataset has been changed.

**Comment by eschmidbauer** [comment]
appears to be the same speaker_info.txt i attached in the first post, thank you for the quick response 
Excited to see results from training this dataset!
