### ISSUE TITLE
Question about inference speed

### ISSUE THREAD

**Issue by seastar105** [CODEJIN/NaturalSpeech2#5]
Thanks for nice repository

You uploaded Inference.ipynb and in notebook, it took 57 seconds for generating audio with 100 steps.

could you inform which environment was used and RTF for generation?

**Comment by CODEJIN** [comment]
Dear @seastar105,

Thank you for your interest in this repository. The reason for the slow inference when using inference.ipynb is likely due to the value '-1' in the second line of the first cell, which results in CPU-based inference. In my testing environment, the GPU was being used for training, so the code is set to '-1'. If you have a GPU and CUDA available in your environment, I recommend changing the value to '0' and testing it.

Best regards,

Heejo

**Comment by seastar105** [comment]
Thanks! I'm gonna check RTF and report here
