### ISSUE TITLE
请问可以小样本克隆音乐吗？

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [CODEJIN/NaturalSpeech2#8]
请问可以小样本克隆音乐吗？

**Comment by CODEJIN** [comment]
Dear @ymmbb8882ymmbb ,

Hello. Please understand that I am not a Chinese speaker, so I am relying on a translator to understand your question and am answering in English. To conclude, this repository does not consider singing voice synthesis (SVS). The paper also assumes SVS, but due to limitations in my resources, I was unable to conduct experiments on that aspect.
It seems that some more work will be needed to proceed with SVS, and I think I will be able to conduct experiments on this in the future if I have more resources.

Best regards.
